name: Lint and Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    name: Frontend Lint & Format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run Prettier
        run: npm run format
      - name: Run ESLint
        run: npm run lint -- --fix

  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Clear Composer cache
        run: composer clear-cache -vvv
      - name: Remove vendor directory
        run: rm -rf vendor
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader -vvv
      - name: Create .env file
        run: cp .env.example .env
      - name: Run backend tests
        run: php test

  backend-lint-format:
    name: Backend Lint & Format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist
      - name: Run PHP-CS-Fixer
        run: vendor/bin/php-cs-fixer fix
      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs -n --standard=PSR12 src/ 